### PR TITLE
Flashing changes

### PR DESCRIPTION
**Pull request by joeFischetti**
Merged upstream code + tested - patching, full flash, cal, and crossflash.

### CODE REVIEW

**Review by Switchleg1 — CHANGES_REQUESTED** [review]
Unable to find a way to make the changes on my end so please remove:

changes to gradle.  
changes to output-metadata.json.
all apk/aab.

**Comment by joeFischetti** [comment]
Lemme know what files specifically and I'll remove them.

**Comment by Switchleg1** [comment]
All except:

constants
udsflash
flashutilities
flashingfragment

**Comment by Switchleg1** [comment]
made changes

**Pull request closed without merging**
